services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./b-contact-api
      target: development
    volumes:
      - ./b-contact-api:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./b-contact-api/.env
    command: npm run start:dev
    ports:
      - 5000:5000
  web:
    build:
      context: ./b-contact-web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./b-contact-web:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: b-contact
    ports:
      - '3306:3306'
    volumes:
    - mysql:/var/lib/mysql
volumes:
  mysql: ~
